[theme]
name = "modern"
[icons]
name = "awesome5"

[[block]]
block = "docker"
format = "{running} {images}"
[[block]]
block = "custom"
command = 'vnstat --oneline --iface enp0s20f0u4+wlp3s0 | cut -d ";" -f6'
interval = 30

[[block]]
block="music"
buttons=["play", "next"]
max_width=8
hide_when_empty=true
on_click="i3-msg scratchpad show"
#on_click="dbus-send --type=method_call --dest=`busctl --user list | grep 'org.mpris.MediaPlayer2'| cut -d ' ' -f1` /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Raise"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
format = "{volume}%"
device_kind = "source"
on_click = "alacritty -e alsamixer"

[[block]]
block = "sound"
format = "{volume}%"
device_kind = "sink"
on_click = "alacritty -e alsamixer"

[[block]]
block = "battery"
device = "BAT1"

[[block]]
block = "time"
format = "%a %d/%m %R"
