[theme]
name = "modern"
[icons]
name = "awesome5"

[[block]]
block = "focused_window"
show_marks = "visible"

[[block]]
block="music"
buttons=["play", "next"]
max_width=8
hide_when_empty=true
on_collapsed_click="spotify"
on_click="dbus-send --type=method_call --dest=`busctl --user list | grep 'org.mpris.MediaPlayer2'| cut -d ' ' -f1` /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Raise"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
on_click = "alacritty -e alsamixer"

[[block]]
block = "battery"
device = "BAT1"

[[block]]
block = "time"
format = "%a %d/%m %R"
