[theme]
name = "modern"
[icons]
name = "awesome5"

[[block]]
block="music"
buttons=["play", "next"]
max_width=8

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "BAT1"

[[block]]
block = "time"
interval = 50
format = "%a %d/%m %R"

