import = [
	"~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
]

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1D202F"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[env]
TERM = "xterm-256color"

[font]
size = 11.8

#[schemes."Gruvbox Dark".bright]
#black = "#928374"
#blue = "#83a598"
#cyan = "#8ec07c"
#green = "#b8bb26"
#magenta = "#d3869b"
#red = "#fb4934"
#white = "#ebdbb2"
#yellow = "#fabd2f"
#
#[schemes."Gruvbox Dark".normal]
#black = "#282828"
#blue = "#458588"
#cyan = "#689d6a"
#green = "#98971a"
#magenta = "#b16286"
#red = "#cc241d"
#white = "#a89984"
#yellow = "#d79921"
#
#[schemes."Gruvbox Dark".primary]
#background = "#282828"
#foreground = "#ebdbb2"
#
#[schemes."Gruvbox Light".bright]
#black = "#928374"
#blue = "#076678"
#cyan = "#427b58"
#green = "#79740e"
#magenta = "#8f3f71"
#red = "#9d0006"
#white = "#3c3836"
#yellow = "#b57614"
#
#[schemes."Gruvbox Light".normal]
#black = "#fbf1c7"
#blue = "#458588"
#cyan = "#689d6a"
#green = "#98971a"
#magenta = "#b16286"
#red = "#cc241d"
#white = "#7c6f64"
#yellow = "#d79921"
#
#[schemes."Gruvbox Light".primary]
#background = "#fbf1c7"
#foreground = "#3c3836"
#
#[[schemes.tokyo_night_dark.indexed_colors]]
#color = "0xff9e64"
#index = 16
#
#[[schemes.tokyo_night_dark.indexed_colors]]
#color = "0xdb4b4b"
#index = 17
#
#[schemes.tokyo_night_dark.bright]
#black = "0x414868"
#blue = "0x7aa2f7"
#cyan = "0x7dcfff"
#green = "0x9ece6a"
#magenta = "0xbb9af7"
#red = "0xf7768e"
#white = "0xc0caf5"
#yellow = "0xe0af68"
#
#[schemes.tokyo_night_dark.normal]
#black = "0x15161E"
#blue = "0x7aa2f7"
#cyan = "0x7dcfff"
#green = "0x9ece6a"
#magenta = "0xbb9af7"
#red = "0xf7768e"
#white = "0xa9b1d6"
#yellow = "0xe0af68"
#
#[schemes.tokyo_night_dark.primary]
#background = "0x1a1b26"
#foreground = "0xc0caf5"
#
#[[schemes.tokyo_night_storm.indexed_colors]]
#color = "0xff9e64"
#index = 16
#
#[[schemes.tokyo_night_storm.indexed_colors]]
#color = "0xdb4b4b"
#index = 17
#
#[schemes.tokyo_night_storm.bright]
#black = "0x414868"
#blue = "0x7aa2f7"
#cyan = "0x7dcfff"
#green = "0x9ece6a"
#magenta = "0xbb9af7"
#red = "0xf7768e"
#white = "0xc0caf5"
#yellow = "0xe0af68"
#
#[schemes.tokyo_night_storm.normal]
#black = "0x1D202F"
#blue = "0x7aa2f7"
#cyan = "0x7dcfff"
#green = "0x9ece6a"
#magenta = "0xbb9af7"
#red = "0xf7768e"
#white = "0xa9b1d6"
#yellow = "0xe0af68"
#
#[schemes.tokyo_night_storm.primary]
#background = "0x24283b"
#foreground = "0xc0caf5"

[scrolling]
history = 10000

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
